version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelsail/php80-composer
    container_name: laravel_app
    ports:
      - 8000:8000
    tty: true
    working_dir: /var/www
