name: DEPLOY TO EC2 INSTANCE AWS
env:
  DEPLOY_PACKAGE_NAME       : "laravel-app_${{ github.sha }}.zip"
  HOST           : ec2-3-98-143-124.ca-central-1.compute.amazonaws.com
on: 
  push:
     branches:
       - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: git clone repository
      uses: actions/checkout@v1
      
    - name: create zip deploy package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*         #don't send github 
      
      #how to connect github with AWS-KEY 
    - name: executing remote ssh using ssh key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AWS_PRIVATE }}
        known_hosts: ${{ env.HOST }}
   - name: run ssh
     run: ssh ec2-user@${{ env.HOST }}
        
