name: DEPLOY TO EC2 INSTANCE AWS
env:
  DEPLOY_PACKAGE_NAME       : "laravel-app_${{ github.sha }}.zip"
  HOST           : ec2-3-98-143-124.ca-central-1.compute.amazonaws.com
  IMAGE_NAME:  laravel_app
on: 
  push:
     branches:
       - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: git clone repository
      uses: actions/checkout@v1
    - name: build image and push
      run: |
        docker build . -t 
        docker login -u netdevopsaslan -p ${{ secrets.DOCKER_PASSWD }} 
        docker build . -t ${{ env.IMAGE_NAME}}:${{ github.sha }}
        
        
  push:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - name: push to repository
      run: |
        docker login -u netdevopsaslan -p ${{ secrets.DOCKER_PASSWD }}
        docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
    
  deploy:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
    - name: deploy to AWS
      run: |
        echo "${{ secrets.AWS_PRIVATE }}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_EC2_PUBLIC_IP }} '
          docker-compose up -d
          '
      
  
      #how to connect github with AWS-KEY 
   
    
        
