name: DEPLOY TO EC2 INSTANCE AWS
env:
  DEPLOY_PACKAGE_NAME       : "laravel-app_${{ github.sha }}.zip"
   
on: 
  push:
     branches:
       - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: git clone repository
      uses: actions/checkout@v1
      
    - name: create zip deploy package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*         #don't send github 
      
      #how to connect github with AWS-KEY 
      
