name: DEPLOY TO EC2 INSTANCE AWS
env:
  DEPLOY_PACKAGE_NAME       : "laravel-app_${{ github.sha }}.zip"
   
on: 
  push:
     branches:
       - master       
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: git clone repository
      uses: actions/checkout@v1
      
    - name: create zip deploy package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*         #don't send github 
      
      #how to connect github with AWS-KEY 
    - name: configure aws secret
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id : $(( secrets.AWS_SECRET_KEY }}
        aws-secret-access-key: ${{secrets.SECRET_KEY }}
        aws-region           : ca-central-1
        
    - name: docker-compose deploy
      run: docker-compose build && up -d 
#
