name: DEPLOY TO EC2 INSTANCE AWS
env:
  DEPLOY_PACKAGE_NAME       : "laravel-app_${{ github.sha }}.zip"
   
on: 
  push:
     branches:
       - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: git clone repository
      uses: actions/checkout@v1
      
    - name: create zip deploy package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*         #don't send github 
      
      #how to connect github with AWS-KEY 
    - name: configure aws secret
      run : ssh -i ${{ secrets.AWS_PRIVATE }} -J ec2-user@ec2-3-98-143-124.ca-central-1.compute.amazonaws.com
        
    - name: docker-compose deploy
      run: docker-compose build && up -d 
