name: DEPLOY TO EC2 INSTANCE AWS
env:
  DEPLOY_PACKAGE_NAME       : "laravel-app_${{ github.sha }}.zip"
  HOST           : ec2-3-98-143-124.ca-central-1.compute.amazonaws.com
  IMAGE_NAME:  laravel_app
on: 
  push:
     branches:
       - main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: netdevopsaslan
          password: ${{ secrets.ACCESS_TOKEN }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: deploy to AWS
      run: |
        echo "${{ secrets.PRIVATE_KEY }}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_EC2_PUBLIC_IP }} '
          docker-compose up -d
          '
      
  
      #how to connect github with AWS-KEY 
   
    
        
